#!/usr/bin/env python3
import argparse
import datetime as dt
import json
import pathlib
import sqlite3


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", required=True, help="Path to CC Switch SQLite database")
    parser.add_argument("--providers", required=True, help="Path to providers JSON generated by Codex-Router")
    parser.add_argument("--backup-dir", default=None, help="Directory to store DB backups")
    args = parser.parse_args()

    db_path = pathlib.Path(args.db)
    providers_path = pathlib.Path(args.providers)
    if not db_path.exists():
        raise RuntimeError(f"CC Switch DB not found: {db_path}")
    if not providers_path.exists():
        raise RuntimeError(f"Providers file not found: {providers_path}")

    backup_dir = pathlib.Path(args.backup_dir) if args.backup_dir else db_path.parent / "backups"
    backup_dir.mkdir(parents=True, exist_ok=True)

    timestamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = backup_dir / f"cc-switch-before-codex-router-{timestamp}.db"

    providers = json.loads(providers_path.read_text(encoding="utf-8"))
    if not isinstance(providers, list):
        providers = [providers]

    connection = sqlite3.connect(db_path, timeout=30)
    try:
        backup = sqlite3.connect(backup_path)
        try:
            connection.backup(backup)
        finally:
            backup.close()

        connection.execute("BEGIN IMMEDIATE")
        for provider in providers:
            settings = {
                "auth": provider.get("auth", {}),
                "config": provider.get("config", {})
            }
            settings.update(provider.get("settings", {}))
            settings_json = json.dumps(settings, ensure_ascii=False, separators=(",", ":"))
            connection.execute(
                "INSERT INTO providers (id, name, app_type, settings_config) "
                "VALUES (?, ?, ?, ?) "
                "ON CONFLICT(id) DO UPDATE SET name=excluded.name, "
                "settings_config=excluded.settings_config",
                (provider["id"], provider["name"], provider.get("app_type", "codex"), settings_json),
            )
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()

    print(f"Synced {len(providers)} provider(s) to CC Switch; backup: {backup_path}")


if __name__ == "__main__":
    main()
