//! Canonical Router error catalog.
use serde::{Deserialize, Serialize};
use std::fmt;

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum RouterErrorCode {
    REQ_0001,
    REQ_0002,
    REQ_0003,
    REQ_0004,
    REQ_0005,
    REQ_0006,
    REQ_0007,
    REQ_0008,
    REQ_0009,
    VAL_0001,
    VAL_0002,
    VAL_0003,
    VAL_0004,
    VAL_0005,
    VAL_0006,
    AUT_0001,
    AUT_0002,
    AUT_0003,
    AUT_0004,
    AUT_0005,
    AUT_0006,
    AUT_0007,
    AUT_0008,
    OAU_0001,
    OAU_0002,
    OAU_0003,
    OAU_0004,
    OAU_0005,
    OAU_0006,
    OAU_0007,
    OAU_0008,
    OAU_0009,
    OAU_0010,
    OAU_0011,
    OAU_0012,
    OAU_0013,
    OAU_0014,
    CFG_0001,
    CFG_0002,
    CFG_0003,
    CFG_0004,
    CFG_0005,
    CFG_0006,
    CFG_0007,
    CFG_0008,
    RTE_0001,
    RTE_0002,
    RTE_0003,
    RTE_0004,
    RTE_0005,
    RTE_0006,
    RTE_0007,
    RTE_0008,
    RTE_0009,
    CLI_0001,
    CLI_0002,
    CLI_0003,
    CLI_0004,
    CLI_0005,
    CLI_0006,
    CLI_0007,
    CLI_0008,
    CLI_0009,
    CLI_0010,
    PRX_0001,
    PRX_0002,
    PRX_0003,
    PRX_0004,
    PRX_0005,
    PRX_0006,
    PRX_0007,
    PRX_0008,
    STR_0001,
    STR_0002,
    STR_0003,
    STR_0004,
    STR_0005,
    STR_0006,
    STR_0007,
    STR_0008,
    STR_0009,
    ADP_0001,
    ADP_0002,
    ADP_0003,
    ADP_0004,
    ADP_0005,
    ADP_0006,
    ADP_0007,
    ADP_0008,
    UP_0001,
    UP_0002,
    UP_0003,
    UP_0004,
    UP_0005,
    UP_0006,
    UP_0007,
    UP_0008,
    UP_0009,
    UP_0010,
    UP_0011,
    UP_0012,
    UP_0013,
    UP_0014,
    STO_0001,
    STO_0002,
    STO_0003,
    STO_0004,
    STO_0005,
    STO_0006,
    STO_0007,
    STO_0008,
    STO_0009,
    STO_0010,
    STO_0011,
    USE_0001,
    USE_0002,
    USE_0003,
    USE_0004,
    USE_0005,
    USE_0006,
    LFC_0001,
    LFC_0002,
    LFC_0003,
    LFC_0004,
    LFC_0005,
    LFC_0006,
    LFC_0007,
    LFC_0008,
    MIG_0001,
    MIG_0002,
    MIG_0003,
    MIG_0004,
    MIG_0005,
    MIG_0006,
    MIG_0007,
    MIG_0008,
    LOG_0001,
    LOG_0002,
    LOG_0003,
    LOG_0004,
    LOG_0005,
    LOG_0006,
    SYS_0001,
    SYS_0002,
    SYS_0003,
    SYS_0004,
}

impl RouterErrorCode {
    pub const ALL: &'static [RouterErrorCode] = &[
        RouterErrorCode::REQ_0001,
        RouterErrorCode::REQ_0002,
        RouterErrorCode::REQ_0003,
        RouterErrorCode::REQ_0004,
        RouterErrorCode::REQ_0005,
        RouterErrorCode::REQ_0006,
        RouterErrorCode::REQ_0007,
        RouterErrorCode::REQ_0008,
        RouterErrorCode::REQ_0009,
        RouterErrorCode::VAL_0001,
        RouterErrorCode::VAL_0002,
        RouterErrorCode::VAL_0003,
        RouterErrorCode::VAL_0004,
        RouterErrorCode::VAL_0005,
        RouterErrorCode::VAL_0006,
        RouterErrorCode::AUT_0001,
        RouterErrorCode::AUT_0002,
        RouterErrorCode::AUT_0003,
        RouterErrorCode::AUT_0004,
        RouterErrorCode::AUT_0005,
        RouterErrorCode::AUT_0006,
        RouterErrorCode::AUT_0007,
        RouterErrorCode::AUT_0008,
        RouterErrorCode::OAU_0001,
        RouterErrorCode::OAU_0002,
        RouterErrorCode::OAU_0003,
        RouterErrorCode::OAU_0004,
        RouterErrorCode::OAU_0005,
        RouterErrorCode::OAU_0006,
        RouterErrorCode::OAU_0007,
        RouterErrorCode::OAU_0008,
        RouterErrorCode::OAU_0009,
        RouterErrorCode::OAU_0010,
        RouterErrorCode::OAU_0011,
        RouterErrorCode::OAU_0012,
        RouterErrorCode::OAU_0013,
        RouterErrorCode::OAU_0014,
        RouterErrorCode::CFG_0001,
        RouterErrorCode::CFG_0002,
        RouterErrorCode::CFG_0003,
        RouterErrorCode::CFG_0004,
        RouterErrorCode::CFG_0005,
        RouterErrorCode::CFG_0006,
        RouterErrorCode::CFG_0007,
        RouterErrorCode::CFG_0008,
        RouterErrorCode::RTE_0001,
        RouterErrorCode::RTE_0002,
        RouterErrorCode::RTE_0003,
        RouterErrorCode::RTE_0004,
        RouterErrorCode::RTE_0005,
        RouterErrorCode::RTE_0006,
        RouterErrorCode::RTE_0007,
        RouterErrorCode::RTE_0008,
        RouterErrorCode::RTE_0009,
        RouterErrorCode::CLI_0001,
        RouterErrorCode::CLI_0002,
        RouterErrorCode::CLI_0003,
        RouterErrorCode::CLI_0004,
        RouterErrorCode::CLI_0005,
        RouterErrorCode::CLI_0006,
        RouterErrorCode::CLI_0007,
        RouterErrorCode::CLI_0008,
        RouterErrorCode::CLI_0009,
        RouterErrorCode::CLI_0010,
        RouterErrorCode::PRX_0001,
        RouterErrorCode::PRX_0002,
        RouterErrorCode::PRX_0003,
        RouterErrorCode::PRX_0004,
        RouterErrorCode::PRX_0005,
        RouterErrorCode::PRX_0006,
        RouterErrorCode::PRX_0007,
        RouterErrorCode::PRX_0008,
        RouterErrorCode::STR_0001,
        RouterErrorCode::STR_0002,
        RouterErrorCode::STR_0003,
        RouterErrorCode::STR_0004,
        RouterErrorCode::STR_0005,
        RouterErrorCode::STR_0006,
        RouterErrorCode::STR_0007,
        RouterErrorCode::STR_0008,
        RouterErrorCode::STR_0009,
        RouterErrorCode::ADP_0001,
        RouterErrorCode::ADP_0002,
        RouterErrorCode::ADP_0003,
        RouterErrorCode::ADP_0004,
        RouterErrorCode::ADP_0005,
        RouterErrorCode::ADP_0006,
        RouterErrorCode::ADP_0007,
        RouterErrorCode::ADP_0008,
        RouterErrorCode::UP_0001,
        RouterErrorCode::UP_0002,
        RouterErrorCode::UP_0003,
        RouterErrorCode::UP_0004,
        RouterErrorCode::UP_0005,
        RouterErrorCode::UP_0006,
        RouterErrorCode::UP_0007,
        RouterErrorCode::UP_0008,
        RouterErrorCode::UP_0009,
        RouterErrorCode::UP_0010,
        RouterErrorCode::UP_0011,
        RouterErrorCode::UP_0012,
        RouterErrorCode::UP_0013,
        RouterErrorCode::UP_0014,
        RouterErrorCode::STO_0001,
        RouterErrorCode::STO_0002,
        RouterErrorCode::STO_0003,
        RouterErrorCode::STO_0004,
        RouterErrorCode::STO_0005,
        RouterErrorCode::STO_0006,
        RouterErrorCode::STO_0007,
        RouterErrorCode::STO_0008,
        RouterErrorCode::STO_0009,
        RouterErrorCode::STO_0010,
        RouterErrorCode::STO_0011,
        RouterErrorCode::USE_0001,
        RouterErrorCode::USE_0002,
        RouterErrorCode::USE_0003,
        RouterErrorCode::USE_0004,
        RouterErrorCode::USE_0005,
        RouterErrorCode::USE_0006,
        RouterErrorCode::LFC_0001,
        RouterErrorCode::LFC_0002,
        RouterErrorCode::LFC_0003,
        RouterErrorCode::LFC_0004,
        RouterErrorCode::LFC_0005,
        RouterErrorCode::LFC_0006,
        RouterErrorCode::LFC_0007,
        RouterErrorCode::LFC_0008,
        RouterErrorCode::MIG_0001,
        RouterErrorCode::MIG_0002,
        RouterErrorCode::MIG_0003,
        RouterErrorCode::MIG_0004,
        RouterErrorCode::MIG_0005,
        RouterErrorCode::MIG_0006,
        RouterErrorCode::MIG_0007,
        RouterErrorCode::MIG_0008,
        RouterErrorCode::LOG_0001,
        RouterErrorCode::LOG_0002,
        RouterErrorCode::LOG_0003,
        RouterErrorCode::LOG_0004,
        RouterErrorCode::LOG_0005,
        RouterErrorCode::LOG_0006,
        RouterErrorCode::SYS_0001,
        RouterErrorCode::SYS_0002,
        RouterErrorCode::SYS_0003,
        RouterErrorCode::SYS_0004,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            RouterErrorCode::REQ_0001 => "CR-REQ-0001",
            RouterErrorCode::REQ_0002 => "CR-REQ-0002",
            RouterErrorCode::REQ_0003 => "CR-REQ-0003",
            RouterErrorCode::REQ_0004 => "CR-REQ-0004",
            RouterErrorCode::REQ_0005 => "CR-REQ-0005",
            RouterErrorCode::REQ_0006 => "CR-REQ-0006",
            RouterErrorCode::REQ_0007 => "CR-REQ-0007",
            RouterErrorCode::REQ_0008 => "CR-REQ-0008",
            RouterErrorCode::REQ_0009 => "CR-REQ-0009",
            RouterErrorCode::VAL_0001 => "CR-VAL-0001",
            RouterErrorCode::VAL_0002 => "CR-VAL-0002",
            RouterErrorCode::VAL_0003 => "CR-VAL-0003",
            RouterErrorCode::VAL_0004 => "CR-VAL-0004",
            RouterErrorCode::VAL_0005 => "CR-VAL-0005",
            RouterErrorCode::VAL_0006 => "CR-VAL-0006",
            RouterErrorCode::AUT_0001 => "CR-AUT-0001",
            RouterErrorCode::AUT_0002 => "CR-AUT-0002",
            RouterErrorCode::AUT_0003 => "CR-AUT-0003",
            RouterErrorCode::AUT_0004 => "CR-AUT-0004",
            RouterErrorCode::AUT_0005 => "CR-AUT-0005",
            RouterErrorCode::AUT_0006 => "CR-AUT-0006",
            RouterErrorCode::AUT_0007 => "CR-AUT-0007",
            RouterErrorCode::AUT_0008 => "CR-AUT-0008",
            RouterErrorCode::OAU_0001 => "CR-OAU-0001",
            RouterErrorCode::OAU_0002 => "CR-OAU-0002",
            RouterErrorCode::OAU_0003 => "CR-OAU-0003",
            RouterErrorCode::OAU_0004 => "CR-OAU-0004",
            RouterErrorCode::OAU_0005 => "CR-OAU-0005",
            RouterErrorCode::OAU_0006 => "CR-OAU-0006",
            RouterErrorCode::OAU_0007 => "CR-OAU-0007",
            RouterErrorCode::OAU_0008 => "CR-OAU-0008",
            RouterErrorCode::OAU_0009 => "CR-OAU-0009",
            RouterErrorCode::OAU_0010 => "CR-OAU-0010",
            RouterErrorCode::OAU_0011 => "CR-OAU-0011",
            RouterErrorCode::OAU_0012 => "CR-OAU-0012",
            RouterErrorCode::OAU_0013 => "CR-OAU-0013",
            RouterErrorCode::OAU_0014 => "CR-OAU-0014",
            RouterErrorCode::CFG_0001 => "CR-CFG-0001",
            RouterErrorCode::CFG_0002 => "CR-CFG-0002",
            RouterErrorCode::CFG_0003 => "CR-CFG-0003",
            RouterErrorCode::CFG_0004 => "CR-CFG-0004",
            RouterErrorCode::CFG_0005 => "CR-CFG-0005",
            RouterErrorCode::CFG_0006 => "CR-CFG-0006",
            RouterErrorCode::CFG_0007 => "CR-CFG-0007",
            RouterErrorCode::CFG_0008 => "CR-CFG-0008",
            RouterErrorCode::RTE_0001 => "CR-RTE-0001",
            RouterErrorCode::RTE_0002 => "CR-RTE-0002",
            RouterErrorCode::RTE_0003 => "CR-RTE-0003",
            RouterErrorCode::RTE_0004 => "CR-RTE-0004",
            RouterErrorCode::RTE_0005 => "CR-RTE-0005",
            RouterErrorCode::RTE_0006 => "CR-RTE-0006",
            RouterErrorCode::RTE_0007 => "CR-RTE-0007",
            RouterErrorCode::RTE_0008 => "CR-RTE-0008",
            RouterErrorCode::RTE_0009 => "CR-RTE-0009",
            RouterErrorCode::CLI_0001 => "CR-CLI-0001",
            RouterErrorCode::CLI_0002 => "CR-CLI-0002",
            RouterErrorCode::CLI_0003 => "CR-CLI-0003",
            RouterErrorCode::CLI_0004 => "CR-CLI-0004",
            RouterErrorCode::CLI_0005 => "CR-CLI-0005",
            RouterErrorCode::CLI_0006 => "CR-CLI-0006",
            RouterErrorCode::CLI_0007 => "CR-CLI-0007",
            RouterErrorCode::CLI_0008 => "CR-CLI-0008",
            RouterErrorCode::CLI_0009 => "CR-CLI-0009",
            RouterErrorCode::CLI_0010 => "CR-CLI-0010",
            RouterErrorCode::PRX_0001 => "CR-PRX-0001",
            RouterErrorCode::PRX_0002 => "CR-PRX-0002",
            RouterErrorCode::PRX_0003 => "CR-PRX-0003",
            RouterErrorCode::PRX_0004 => "CR-PRX-0004",
            RouterErrorCode::PRX_0005 => "CR-PRX-0005",
            RouterErrorCode::PRX_0006 => "CR-PRX-0006",
            RouterErrorCode::PRX_0007 => "CR-PRX-0007",
            RouterErrorCode::PRX_0008 => "CR-PRX-0008",
            RouterErrorCode::STR_0001 => "CR-STR-0001",
            RouterErrorCode::STR_0002 => "CR-STR-0002",
            RouterErrorCode::STR_0003 => "CR-STR-0003",
            RouterErrorCode::STR_0004 => "CR-STR-0004",
            RouterErrorCode::STR_0005 => "CR-STR-0005",
            RouterErrorCode::STR_0006 => "CR-STR-0006",
            RouterErrorCode::STR_0007 => "CR-STR-0007",
            RouterErrorCode::STR_0008 => "CR-STR-0008",
            RouterErrorCode::STR_0009 => "CR-STR-0009",
            RouterErrorCode::ADP_0001 => "CR-ADP-0001",
            RouterErrorCode::ADP_0002 => "CR-ADP-0002",
            RouterErrorCode::ADP_0003 => "CR-ADP-0003",
            RouterErrorCode::ADP_0004 => "CR-ADP-0004",
            RouterErrorCode::ADP_0005 => "CR-ADP-0005",
            RouterErrorCode::ADP_0006 => "CR-ADP-0006",
            RouterErrorCode::ADP_0007 => "CR-ADP-0007",
            RouterErrorCode::ADP_0008 => "CR-ADP-0008",
            RouterErrorCode::UP_0001 => "CR-UP-0001",
            RouterErrorCode::UP_0002 => "CR-UP-0002",
            RouterErrorCode::UP_0003 => "CR-UP-0003",
            RouterErrorCode::UP_0004 => "CR-UP-0004",
            RouterErrorCode::UP_0005 => "CR-UP-0005",
            RouterErrorCode::UP_0006 => "CR-UP-0006",
            RouterErrorCode::UP_0007 => "CR-UP-0007",
            RouterErrorCode::UP_0008 => "CR-UP-0008",
            RouterErrorCode::UP_0009 => "CR-UP-0009",
            RouterErrorCode::UP_0010 => "CR-UP-0010",
            RouterErrorCode::UP_0011 => "CR-UP-0011",
            RouterErrorCode::UP_0012 => "CR-UP-0012",
            RouterErrorCode::UP_0013 => "CR-UP-0013",
            RouterErrorCode::UP_0014 => "CR-UP-0014",
            RouterErrorCode::STO_0001 => "CR-STO-0001",
            RouterErrorCode::STO_0002 => "CR-STO-0002",
            RouterErrorCode::STO_0003 => "CR-STO-0003",
            RouterErrorCode::STO_0004 => "CR-STO-0004",
            RouterErrorCode::STO_0005 => "CR-STO-0005",
            RouterErrorCode::STO_0006 => "CR-STO-0006",
            RouterErrorCode::STO_0007 => "CR-STO-0007",
            RouterErrorCode::STO_0008 => "CR-STO-0008",
            RouterErrorCode::STO_0009 => "CR-STO-0009",
            RouterErrorCode::STO_0010 => "CR-STO-0010",
            RouterErrorCode::STO_0011 => "CR-STO-0011",
            RouterErrorCode::USE_0001 => "CR-USE-0001",
            RouterErrorCode::USE_0002 => "CR-USE-0002",
            RouterErrorCode::USE_0003 => "CR-USE-0003",
            RouterErrorCode::USE_0004 => "CR-USE-0004",
            RouterErrorCode::USE_0005 => "CR-USE-0005",
            RouterErrorCode::USE_0006 => "CR-USE-0006",
            RouterErrorCode::LFC_0001 => "CR-LFC-0001",
            RouterErrorCode::LFC_0002 => "CR-LFC-0002",
            RouterErrorCode::LFC_0003 => "CR-LFC-0003",
            RouterErrorCode::LFC_0004 => "CR-LFC-0004",
            RouterErrorCode::LFC_0005 => "CR-LFC-0005",
            RouterErrorCode::LFC_0006 => "CR-LFC-0006",
            RouterErrorCode::LFC_0007 => "CR-LFC-0007",
            RouterErrorCode::LFC_0008 => "CR-LFC-0008",
            RouterErrorCode::MIG_0001 => "CR-MIG-0001",
            RouterErrorCode::MIG_0002 => "CR-MIG-0002",
            RouterErrorCode::MIG_0003 => "CR-MIG-0003",
            RouterErrorCode::MIG_0004 => "CR-MIG-0004",
            RouterErrorCode::MIG_0005 => "CR-MIG-0005",
            RouterErrorCode::MIG_0006 => "CR-MIG-0006",
            RouterErrorCode::MIG_0007 => "CR-MIG-0007",
            RouterErrorCode::MIG_0008 => "CR-MIG-0008",
            RouterErrorCode::LOG_0001 => "CR-LOG-0001",
            RouterErrorCode::LOG_0002 => "CR-LOG-0002",
            RouterErrorCode::LOG_0003 => "CR-LOG-0003",
            RouterErrorCode::LOG_0004 => "CR-LOG-0004",
            RouterErrorCode::LOG_0005 => "CR-LOG-0005",
            RouterErrorCode::LOG_0006 => "CR-LOG-0006",
            RouterErrorCode::SYS_0001 => "CR-SYS-0001",
            RouterErrorCode::SYS_0002 => "CR-SYS-0002",
            RouterErrorCode::SYS_0003 => "CR-SYS-0003",
            RouterErrorCode::SYS_0004 => "CR-SYS-0004",
        }
    }

    pub const fn metadata(self) -> ErrorMetadata {
        match self {
            RouterErrorCode::REQ_0001 => ErrorMetadata {
                code: "CR-REQ-0001",
                scenario: "HTTP 方法不受该旧接口支持",
                http_status: 405,
                retry: RetryPolicy::No,
                agent_action: "核对接口映射中的 method",
            },
            RouterErrorCode::REQ_0002 => ErrorMetadata {
                code: "CR-REQ-0002",
                scenario: "请求路径不在兼容路由表",
                http_status: 404,
                retry: RetryPolicy::No,
                agent_action: "核对 path/版本前缀",
            },
            RouterErrorCode::REQ_0003 => ErrorMetadata {
                code: "CR-REQ-0003",
                scenario: "请求头超过 64 KiB",
                http_status: 431,
                retry: RetryPolicy::No,
                agent_action: "删除非必要 header",
            },
            RouterErrorCode::REQ_0004 => ErrorMetadata {
                code: "CR-REQ-0004",
                scenario: "请求体超过该接口限制",
                http_status: 413,
                retry: RetryPolicy::No,
                agent_action: "缩小输入或使用任务接口",
            },
            RouterErrorCode::REQ_0005 => ErrorMetadata {
                code: "CR-REQ-0005",
                scenario: "接收请求头/体超时",
                http_status: 408,
                retry: RetryPolicy::Bounded,
                agent_action: "检查本地客户端连接",
            },
            RouterErrorCode::REQ_0006 => ErrorMetadata {
                code: "CR-REQ-0006",
                scenario: "JSON 或 multipart 语法无效",
                http_status: 400,
                retry: RetryPolicy::No,
                agent_action: "按接口 schema 修正 payload",
            },
            RouterErrorCode::REQ_0007 => ErrorMetadata {
                code: "CR-REQ-0007",
                scenario: "外部 request ID 含非法字符/过长",
                http_status: 400,
                retry: RetryPolicy::No,
                agent_action: "删除该 header 让 Router 生成",
            },
            RouterErrorCode::REQ_0008 => ErrorMetadata {
                code: "CR-REQ-0008",
                scenario: "客户端在执行前取消",
                http_status: 499,
                retry: RetryPolicy::No,
                agent_action: "仅在任务仍需要时重新请求",
            },
            RouterErrorCode::REQ_0009 => ErrorMetadata {
                code: "CR-REQ-0009",
                scenario: "请求的任务/批次/条目不存在",
                http_status: 404,
                retry: RetryPolicy::No,
                agent_action: "确认 id 或先提交任务",
            },
            RouterErrorCode::VAL_0001 => ErrorMetadata {
                code: "CR-VAL-0001",
                scenario: "必填 model 缺失",
                http_status: 400,
                retry: RetryPolicy::No,
                agent_action: "提供公开模型 ID",
            },
            RouterErrorCode::VAL_0002 => ErrorMetadata {
                code: "CR-VAL-0002",
                scenario: "模型 ID 不在 Router catalog",
                http_status: 404,
                retry: RetryPolicy::No,
                agent_action: "先查询 /v1/models",
            },
            RouterErrorCode::VAL_0003 => ErrorMetadata {
                code: "CR-VAL-0003",
                scenario: "参数类型/范围违反接口 schema",
                http_status: 400,
                retry: RetryPolicy::No,
                agent_action: "按 field 修正参数",
            },
            RouterErrorCode::VAL_0004 => ErrorMetadata {
                code: "CR-VAL-0004",
                scenario: "模型缺少凭据引用",
                http_status: 422,
                retry: RetryPolicy::Operator,
                agent_action: "在 Router 配置中绑定凭据",
            },
            RouterErrorCode::VAL_0005 => ErrorMetadata {
                code: "CR-VAL-0005",
                scenario: "后端/管理地址不是允许的 loopback HTTP",
                http_status: 400,
                retry: RetryPolicy::Operator,
                agent_action: "恢复默认本地地址",
            },
            RouterErrorCode::VAL_0006 => ErrorMetadata {
                code: "CR-VAL-0006",
                scenario: "auth/任务文件名或路径可能逃逸目录",
                http_status: 400,
                retry: RetryPolicy::No,
                agent_action: "使用纯文件名/合法 task id",
            },
            RouterErrorCode::AUT_0001 => ErrorMetadata {
                code: "CR-AUT-0001",
                scenario: "数据面 Bearer Key 缺失",
                http_status: 401,
                retry: RetryPolicy::No,
                agent_action: "使用 Router 本地 API Key",
            },
            RouterErrorCode::AUT_0002 => ErrorMetadata {
                code: "CR-AUT-0002",
                scenario: "数据面 Bearer Key 无效/已吊销",
                http_status: 401,
                retry: RetryPolicy::Operator,
                agent_action: "更新客户端 Key",
            },
            RouterErrorCode::AUT_0003 => ErrorMetadata {
                code: "CR-AUT-0003",
                scenario: "Router AdminPassword 不存在",
                http_status: 503,
                retry: RetryPolicy::Operator,
                agent_action: "运行本地管理员初始化",
            },
            RouterErrorCode::AUT_0004 => ErrorMetadata {
                code: "CR-AUT-0004",
                scenario: "旧 admin 登录邮箱/密码无效",
                http_status: 401,
                retry: RetryPolicy::No,
                agent_action: "使用本机管理员凭据",
            },
            RouterErrorCode::AUT_0005 => ErrorMetadata {
                code: "CR-AUT-0005",
                scenario: "CLI management secret 不存在",
                http_status: 503,
                retry: RetryPolicy::Operator,
                agent_action: "重新生成并写凭据库",
            },
            RouterErrorCode::AUT_0006 => ErrorMetadata {
                code: "CR-AUT-0006",
                scenario: "CLI management 鉴权被拒绝",
                http_status: 502,
                retry: RetryPolicy::Operator,
                agent_action: "轮换并同步 management secret",
            },
            RouterErrorCode::AUT_0007 => ErrorMetadata {
                code: "CR-AUT-0007",
                scenario: "OAuth 凭据过期且刷新失败",
                http_status: 401,
                retry: RetryPolicy::Operator,
                agent_action: "对该账号重新授权",
            },
            RouterErrorCode::AUT_0008 => ErrorMetadata {
                code: "CR-AUT-0008",
                scenario: "凭据已由用户禁用",
                http_status: 503,
                retry: RetryPolicy::Operator,
                agent_action: "启用账号或选择其他路由",
            },
            RouterErrorCode::OAU_0001 => ErrorMetadata {
                code: "CR-OAU-0001",
                scenario: "请求的 OAuth provider 未支持",
                http_status: 400,
                retry: RetryPolicy::No,
                agent_action: "使用五类受支持 provider",
            },
            RouterErrorCode::OAU_0002 => ErrorMetadata {
                code: "CR-OAU-0002",
                scenario: "OAuth callback 端口被其他进程占用",
                http_status: 409,
                retry: RetryPolicy::Operator,
                agent_action: "关闭占用者后重试",
            },
            RouterErrorCode::OAU_0003 => ErrorMetadata {
                code: "CR-OAU-0003",
                scenario: "生成 authorization URL 失败",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "检查网络/CLI OAuth handler",
            },
            RouterErrorCode::OAU_0004 => ErrorMetadata {
                code: "CR-OAU-0004",
                scenario: "OAuth callback state 不匹配",
                http_status: 400,
                retry: RetryPolicy::No,
                agent_action: "丢弃会话并重新登录",
            },
            RouterErrorCode::OAU_0005 => ErrorMetadata {
                code: "CR-OAU-0005",
                scenario: "OAuth callback/device flow 超时",
                http_status: 408,
                retry: RetryPolicy::No,
                agent_action: "重新发起登录并在 5 分钟内完成",
            },
            RouterErrorCode::OAU_0006 => ErrorMetadata {
                code: "CR-OAU-0006",
                scenario: "用户取消 OAuth 会话",
                http_status: 409,
                retry: RetryPolicy::No,
                agent_action: "无需修复",
            },
            RouterErrorCode::OAU_0007 => ErrorMetadata {
                code: "CR-OAU-0007",
                scenario: "authorization code/token 交换失败",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "检查 provider 返回并重新授权",
            },
            RouterErrorCode::OAU_0008 => ErrorMetadata {
                code: "CR-OAU-0008",
                scenario: "token 交换成功但 access/refresh token 缺失",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "保留原账号并报告 provider 异常",
            },
            RouterErrorCode::OAU_0009 => ErrorMetadata {
                code: "CR-OAU-0009",
                scenario: "无法由 provider claims 得到稳定身份",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "不创建账号，更新适配器字段",
            },
            RouterErrorCode::OAU_0010 => ErrorMetadata {
                code: "CR-OAU-0010",
                scenario: "重复身份账号合并事务失败",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "回滚新 auth file 后重试",
            },
            RouterErrorCode::OAU_0011 => ErrorMetadata {
                code: "CR-OAU-0011",
                scenario: "CLI auth file 保存/ACL 设置失败",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "修复 auth 目录权限/磁盘",
            },
            RouterErrorCode::OAU_0012 => ErrorMetadata {
                code: "CR-OAU-0012",
                scenario: "OAuth state 未知或已过期",
                http_status: 410,
                retry: RetryPolicy::No,
                agent_action: "重新发起 OAuth",
            },
            RouterErrorCode::OAU_0013 => ErrorMetadata {
                code: "CR-OAU-0013",
                scenario: "Gemini CLI 插件/适配器不可用",
                http_status: 503,
                retry: RetryPolicy::Operator,
                agent_action: "修复随包插件版本/加载错误",
            },
            RouterErrorCode::OAU_0014 => ErrorMetadata {
                code: "CR-OAU-0014",
                scenario: "Grok SSO token 转换被上游拒绝",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "只替换失败 token，保留成功项",
            },
            RouterErrorCode::CFG_0001 => ErrorMetadata {
                code: "CR-CFG-0001",
                scenario: "Router 配置无法读取/解析",
                http_status: 500,
                retry: RetryPolicy::Operator,
                agent_action: "从备份恢复或修正配置",
            },
            RouterErrorCode::CFG_0002 => ErrorMetadata {
                code: "CR-CFG-0002",
                scenario: "配置 schema 高于当前程序支持",
                http_status: 409,
                retry: RetryPolicy::Operator,
                agent_action: "使用匹配版本程序",
            },
            RouterErrorCode::CFG_0003 => ErrorMetadata {
                code: "CR-CFG-0003",
                scenario: "有类型 CLI 配置渲染失败",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "修复配置编译器字段映射",
            },
            RouterErrorCode::CFG_0004 => ErrorMetadata {
                code: "CR-CFG-0004",
                scenario: "候选 CLI 配置静态校验失败",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "修正冲突/非法 provider 配置",
            },
            RouterErrorCode::CFG_0005 => ErrorMetadata {
                code: "CR-CFG-0005",
                scenario: "CLI 热加载候选配置失败",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "恢复上一快照并检查 CLI 日志事件",
            },
            RouterErrorCode::CFG_0006 => ErrorMetadata {
                code: "CR-CFG-0006",
                scenario: "编译后没有任何公开可服务模型",
                http_status: 422,
                retry: RetryPolicy::Operator,
                agent_action: "启用账号或添加 API 渠道",
            },
            RouterErrorCode::CFG_0007 => ErrorMetadata {
                code: "CR-CFG-0007",
                scenario: "公开别名/内部 prefix 冲突",
                http_status: 409,
                retry: RetryPolicy::No,
                agent_action: "调整别名或路由唯一键",
            },
            RouterErrorCode::CFG_0008 => ErrorMetadata {
                code: "CR-CFG-0008",
                scenario: "18080/18081/18082 端口被非预期进程占用",
                http_status: 409,
                retry: RetryPolicy::Operator,
                agent_action: "核对 PID/路径后释放端口",
            },
            RouterErrorCode::RTE_0001 => ErrorMetadata {
                code: "CR-RTE-0001",
                scenario: "公开模型没有匹配路由",
                http_status: 404,
                retry: RetryPolicy::No,
                agent_action: "修复 composite route/catalog",
            },
            RouterErrorCode::RTE_0002 => ErrorMetadata {
                code: "CR-RTE-0002",
                scenario: "匹配 pool 中无可调度凭据",
                http_status: 503,
                retry: RetryPolicy::After,
                agent_action: "等待 reset 或恢复账号",
            },
            RouterErrorCode::RTE_0003 => ErrorMetadata {
                code: "CR-RTE-0003",
                scenario: "复合路由解析出现多义/非法结果",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "修复路由编译器或重复数据",
            },
            RouterErrorCode::RTE_0004 => ErrorMetadata {
                code: "CR-RTE-0004",
                scenario: "所有跨 provider fallback 均失败",
                http_status: 502,
                retry: RetryPolicy::After,
                agent_action: "根据 attempts 修复首个非瞬态失败",
            },
            RouterErrorCode::RTE_0005 => ErrorMetadata {
                code: "CR-RTE-0005",
                scenario: "session binding 指向已删除 pool",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "清理无效 binding 并重新选路",
            },
            RouterErrorCode::RTE_0006 => ErrorMetadata {
                code: "CR-RTE-0006",
                scenario: "continuation 请求缺少可恢复 owner",
                http_status: 409,
                retry: RetryPolicy::No,
                agent_action: "新建会话，勿跨账号续接",
            },
            RouterErrorCode::RTE_0007 => ErrorMetadata {
                code: "CR-RTE-0007",
                scenario: "public/internal model 双向改写失败",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "修复模型映射",
            },
            RouterErrorCode::RTE_0008 => ErrorMetadata {
                code: "CR-RTE-0008",
                scenario: "fallback 总尝试预算耗尽",
                http_status: 503,
                retry: RetryPolicy::After,
                agent_action: "遵循最短 reset/Retry-After",
            },
            RouterErrorCode::RTE_0009 => ErrorMetadata {
                code: "CR-RTE-0009",
                scenario: "路由 policy 含不支持的 endpoint/platform",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "修正 composite route",
            },
            RouterErrorCode::CLI_0001 => ErrorMetadata {
                code: "CR-CLI-0001",
                scenario: "锁定的 CLIProxyAPI 可执行文件缺失/哈希不符",
                http_status: 503,
                retry: RetryPolicy::Operator,
                agent_action: "恢复发布负载",
            },
            RouterErrorCode::CLI_0002 => ErrorMetadata {
                code: "CR-CLI-0002",
                scenario: "CLIProxyAPI 进程启动失败",
                http_status: 503,
                retry: RetryPolicy::Bounded,
                agent_action: "检查配置、端口、ACL",
            },
            RouterErrorCode::CLI_0003 => ErrorMetadata {
                code: "CR-CLI-0003",
                scenario: "CLI /healthz 启动超时",
                http_status: 504,
                retry: RetryPolicy::Bounded,
                agent_action: "检查 CLI stderr/配置加载",
            },
            RouterErrorCode::CLI_0004 => ErrorMetadata {
                code: "CR-CLI-0004",
                scenario: "CLI 在请求处理中意外退出",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "由 supervisor 重启并保留 crash 事件",
            },
            RouterErrorCode::CLI_0005 => ErrorMetadata {
                code: "CR-CLI-0005",
                scenario: "/v0/management 未启用/返回 404",
                http_status: 502,
                retry: RetryPolicy::Operator,
                agent_action: "配置 management secret 且关闭 Home mode",
            },
            RouterErrorCode::CLI_0006 => ErrorMetadata {
                code: "CR-CLI-0006",
                scenario: "CLI management 返回无法解析的响应",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "核对锁定版本 API 合同",
            },
            RouterErrorCode::CLI_0007 => ErrorMetadata {
                code: "CR-CLI-0007",
                scenario: "CLI auth registry reload 后对象缺失",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "回滚配置/auth file 并重新加载",
            },
            RouterErrorCode::CLI_0008 => ErrorMetadata {
                code: "CR-CLI-0008",
                scenario: "CLI 数据面拒绝 Router 已验证请求",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "检查协议适配和 provider 选择",
            },
            RouterErrorCode::CLI_0009 => ErrorMetadata {
                code: "CR-CLI-0009",
                scenario: "CLI 不支持请求协议/子路径",
                http_status: 501,
                retry: RetryPolicy::No,
                agent_action: "走 Router legacy adapter 或补实现",
            },
            RouterErrorCode::CLI_0010 => ErrorMetadata {
                code: "CR-CLI-0010",
                scenario: "CLI reset quota/cooldown 失败",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "保持账号隔离，稍后 probe",
            },
            RouterErrorCode::PRX_0001 => ErrorMetadata {
                code: "CR-PRX-0001",
                scenario: "代理 URL 语法无效",
                http_status: 400,
                retry: RetryPolicy::No,
                agent_action: "使用 http/https/socks5 URL",
            },
            RouterErrorCode::PRX_0002 => ErrorMetadata {
                code: "CR-PRX-0002",
                scenario: "代理协议不受支持",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "更换受支持协议",
            },
            RouterErrorCode::PRX_0003 => ErrorMetadata {
                code: "CR-PRX-0003",
                scenario: "代理凭据缺失/认证失败",
                http_status: 407,
                retry: RetryPolicy::Operator,
                agent_action: "更新代理凭据引用",
            },
            RouterErrorCode::PRX_0004 => ErrorMetadata {
                code: "CR-PRX-0004",
                scenario: "无法连接代理服务器",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "检查代理进程/地址",
            },
            RouterErrorCode::PRX_0005 => ErrorMetadata {
                code: "CR-PRX-0005",
                scenario: "代理/上游 DNS 解析失败",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "检查 DNS 与代理解析模式",
            },
            RouterErrorCode::PRX_0006 => ErrorMetadata {
                code: "CR-PRX-0006",
                scenario: "代理/上游 TLS 握手或证书失败",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "检查系统时间/证书/中间代理",
            },
            RouterErrorCode::PRX_0007 => ErrorMetadata {
                code: "CR-PRX-0007",
                scenario: "代理链路超时",
                http_status: 504,
                retry: RetryPolicy::Bounded,
                agent_action: "检查代理延迟与超时配置",
            },
            RouterErrorCode::PRX_0008 => ErrorMetadata {
                code: "CR-PRX-0008",
                scenario: "策略禁止代理失败后的直连回退",
                http_status: 503,
                retry: RetryPolicy::No,
                agent_action: "修复代理；不得自动绕过策略",
            },
            RouterErrorCode::STR_0001 => ErrorMetadata {
                code: "CR-STR-0001",
                scenario: "等待上游响应头超时",
                http_status: 504,
                retry: RetryPolicy::Bounded,
                agent_action: "检查上游/代理，允许未发送前切换",
            },
            RouterErrorCode::STR_0002 => ErrorMetadata {
                code: "CR-STR-0002",
                scenario: "首个业务字节超时",
                http_status: 504,
                retry: RetryPolicy::Bounded,
                agent_action: "仅在未向客户端发送业务字节时重试",
            },
            RouterErrorCode::STR_0003 => ErrorMetadata {
                code: "CR-STR-0003",
                scenario: "流超过最大静默时间",
                http_status: 504,
                retry: RetryPolicy::No,
                agent_action: "终止该流并新建请求",
            },
            RouterErrorCode::STR_0004 => ErrorMetadata {
                code: "CR-STR-0004",
                scenario: "chunked frame 无效/截断",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "记录 CLI/upstream 版本和 request_id",
            },
            RouterErrorCode::STR_0005 => ErrorMetadata {
                code: "CR-STR-0005",
                scenario: "SSE event 无法解析",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "修复 provider response adapter",
            },
            RouterErrorCode::STR_0006 => ErrorMetadata {
                code: "CR-STR-0006",
                scenario: "SSE/WS 在无终止事件时关闭",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "合成明确 failed event，不标成功",
            },
            RouterErrorCode::STR_0007 => ErrorMetadata {
                code: "CR-STR-0007",
                scenario: "客户端在流中断开",
                http_status: 499,
                retry: RetryPolicy::No,
                agent_action: "取消上游并释放 account slot",
            },
            RouterErrorCode::STR_0008 => ErrorMetadata {
                code: "CR-STR-0008",
                scenario: "WebSocket upgrade 失败",
                http_status: 400,
                retry: RetryPolicy::No,
                agent_action: "核对 upgrade/auth headers",
            },
            RouterErrorCode::STR_0009 => ErrorMetadata {
                code: "CR-STR-0009",
                scenario: "WebSocket 双向 relay 失败",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "关闭两端并释放 continuation owner",
            },
            RouterErrorCode::ADP_0001 => ErrorMetadata {
                code: "CR-ADP-0001",
                scenario: "请求协议转换失败",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "根据 source_format/target_format 修适配",
            },
            RouterErrorCode::ADP_0002 => ErrorMetadata {
                code: "CR-ADP-0002",
                scenario: "响应协议转换失败",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "保留脱敏原始类型信息并修适配",
            },
            RouterErrorCode::ADP_0003 => ErrorMetadata {
                code: "CR-ADP-0003",
                scenario: "Responses/Chat 转换丢失必需字段",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "增加转换契约测试",
            },
            RouterErrorCode::ADP_0004 => ErrorMetadata {
                code: "CR-ADP-0004",
                scenario: "tool 声明/调用/输出无法配对",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "修复 call_id/name 映射",
            },
            RouterErrorCode::ADP_0005 => ErrorMetadata {
                code: "CR-ADP-0005",
                scenario: "加密 reasoning/tool 内容不能安全转发",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "清除不兼容字段并要求新会话",
            },
            RouterErrorCode::ADP_0006 => ErrorMetadata {
                code: "CR-ADP-0006",
                scenario: "compact 输入无法生成合法续接内容",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "降低输入或修复 compact adapter",
            },
            RouterErrorCode::ADP_0007 => ErrorMetadata {
                code: "CR-ADP-0007",
                scenario: "选定 route 不支持图片输入",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "选择多模态 route；仅按既有规则降级",
            },
            RouterErrorCode::ADP_0008 => ErrorMetadata {
                code: "CR-ADP-0008",
                scenario: "无法生成旧接口响应 envelope",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "修复对应协议 serializer",
            },
            RouterErrorCode::UP_0001 => ErrorMetadata {
                code: "CR-UP-0001",
                scenario: "上游 400 且非本地转换问题",
                http_status: 400,
                retry: RetryPolicy::No,
                agent_action: "修正请求参数",
            },
            RouterErrorCode::UP_0002 => ErrorMetadata {
                code: "CR-UP-0002",
                scenario: "上游 401 凭据无效",
                http_status: 502,
                retry: RetryPolicy::Operator,
                agent_action: "刷新/更换该账号；不得误封其他账号",
            },
            RouterErrorCode::UP_0003 => ErrorMetadata {
                code: "CR-UP-0003",
                scenario: "上游 403 权限/额度拒绝",
                http_status: 502,
                retry: RetryPolicy::After,
                agent_action: "区分权限与 quota 后处理",
            },
            RouterErrorCode::UP_0004 => ErrorMetadata {
                code: "CR-UP-0004",
                scenario: "上游模型/资源 404",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "同步模型或修正 upstream_model",
            },
            RouterErrorCode::UP_0005 => ErrorMetadata {
                code: "CR-UP-0005",
                scenario: "上游 408",
                http_status: 504,
                retry: RetryPolicy::Bounded,
                agent_action: "在总预算内换凭据",
            },
            RouterErrorCode::UP_0006 => ErrorMetadata {
                code: "CR-UP-0006",
                scenario: "上游 409 会话/状态冲突",
                http_status: 409,
                retry: RetryPolicy::No,
                agent_action: "保持 owner，按上游建议重建会话",
            },
            RouterErrorCode::UP_0007 => ErrorMetadata {
                code: "CR-UP-0007",
                scenario: "上游拒绝过大请求",
                http_status: 413,
                retry: RetryPolicy::No,
                agent_action: "compact 或减少输入",
            },
            RouterErrorCode::UP_0008 => ErrorMetadata {
                code: "CR-UP-0008",
                scenario: "上游 429",
                http_status: 429,
                retry: RetryPolicy::After,
                agent_action: "记录 reset/Retry-After，冷却当前凭据",
            },
            RouterErrorCode::UP_0009 => ErrorMetadata {
                code: "CR-UP-0009",
                scenario: "上游 500",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "换凭据/route，受总预算限制",
            },
            RouterErrorCode::UP_0010 => ErrorMetadata {
                code: "CR-UP-0010",
                scenario: "上游 502",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "同上",
            },
            RouterErrorCode::UP_0011 => ErrorMetadata {
                code: "CR-UP-0011",
                scenario: "上游 503",
                http_status: 503,
                retry: RetryPolicy::After,
                agent_action: "同上并尊重 Retry-After",
            },
            RouterErrorCode::UP_0012 => ErrorMetadata {
                code: "CR-UP-0012",
                scenario: "上游 504",
                http_status: 504,
                retry: RetryPolicy::Bounded,
                agent_action: "同上",
            },
            RouterErrorCode::UP_0013 => ErrorMetadata {
                code: "CR-UP-0013",
                scenario: "上游成功状态但 payload 非法",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "保存脱敏结构摘要并修 provider adapter",
            },
            RouterErrorCode::UP_0014 => ErrorMetadata {
                code: "CR-UP-0014",
                scenario: "上游连接被重置/提前 EOF",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "未开始流时可换凭据",
            },
            RouterErrorCode::STO_0001 => ErrorMetadata {
                code: "CR-STO-0001",
                scenario: "SQLite 无法打开/创建",
                http_status: 500,
                retry: RetryPolicy::Operator,
                agent_action: "检查磁盘、ACL、路径",
            },
            RouterErrorCode::STO_0002 => ErrorMetadata {
                code: "CR-STO-0002",
                scenario: "SQLite schema migration 失败",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "从迁移前备份恢复",
            },
            RouterErrorCode::STO_0003 => ErrorMetadata {
                code: "CR-STO-0003",
                scenario: "状态读取失败",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "检查数据库健康/锁",
            },
            RouterErrorCode::STO_0004 => ErrorMetadata {
                code: "CR-STO-0004",
                scenario: "状态事务写入失败",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "保持旧配置，重试事务",
            },
            RouterErrorCode::STO_0005 => ErrorMetadata {
                code: "CR-STO-0005",
                scenario: "SQLite busy 超过 bounded timeout",
                http_status: 503,
                retry: RetryPolicy::Bounded,
                agent_action: "检查长事务/单写队列",
            },
            RouterErrorCode::STO_0006 => ErrorMetadata {
                code: "CR-STO-0006",
                scenario: "SQLite integrity check 失败",
                http_status: 500,
                retry: RetryPolicy::Operator,
                agent_action: "停止切换并从备份恢复",
            },
            RouterErrorCode::STO_0007 => ErrorMetadata {
                code: "CR-STO-0007",
                scenario: "数字 account ID 找不到 auth 映射",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "修复 mapping/migration journal",
            },
            RouterErrorCode::STO_0008 => ErrorMetadata {
                code: "CR-STO-0008",
                scenario: "stable identity/auth_index 唯一约束冲突",
                http_status: 409,
                retry: RetryPolicy::No,
                agent_action: "执行确定性去重",
            },
            RouterErrorCode::STO_0009 => ErrorMetadata {
                code: "CR-STO-0009",
                scenario: "request ledger 终态写入失败",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "进入 degraded，禁止宣称统计完整",
            },
            RouterErrorCode::STO_0010 => ErrorMetadata {
                code: "CR-STO-0010",
                scenario: "SQLite 备份/快照失败",
                http_status: 500,
                retry: RetryPolicy::Operator,
                agent_action: "未取得备份前禁止切换",
            },
            RouterErrorCode::STO_0011 => ErrorMetadata {
                code: "CR-STO-0011",
                scenario: "任务输出文件写入/读取失败",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "检查任务目录 ACL 与磁盘空间",
            },
            RouterErrorCode::USE_0001 => ErrorMetadata {
                code: "CR-USE-0001",
                scenario: "provider usage/quota payload 无法解析",
                http_status: 502,
                retry: RetryPolicy::No,
                agent_action: "更新对应 normalize adapter",
            },
            RouterErrorCode::USE_0002 => ErrorMetadata {
                code: "CR-USE-0002",
                scenario: "CLI usage queue 发生记录丢弃",
                http_status: 503,
                retry: RetryPolicy::Bounded,
                agent_action: "提高消费速度；以 Router ledger 为准",
            },
            RouterErrorCode::USE_0003 => ErrorMetadata {
                code: "CR-USE-0003",
                scenario: "provider 实时额度不可用",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "显示缓存并标 stale，不伪造可用额度",
            },
            RouterErrorCode::USE_0004 => ErrorMetadata {
                code: "CR-USE-0004",
                scenario: "未配置模型价格，成本无法计算",
                http_status: 200,
                retry: RetryPolicy::No,
                agent_action: "返回 tokens 且 cost_known=false",
            },
            RouterErrorCode::USE_0005 => ErrorMetadata {
                code: "CR-USE-0005",
                scenario: "CLI usage 与 Router ledger 对账不一致",
                http_status: 500,
                retry: RetryPolicy::Operator,
                agent_action: "按 request_id 查缺失终态/重复入账",
            },
            RouterErrorCode::USE_0006 => ErrorMetadata {
                code: "CR-USE-0006",
                scenario: "ledger retention/聚合任务失败",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "保留原始 ledger，重跑聚合",
            },
            RouterErrorCode::LFC_0001 => ErrorMetadata {
                code: "CR-LFC-0001",
                scenario: "生命周期锁等待超时",
                http_status: 409,
                retry: RetryPolicy::Bounded,
                agent_action: "等当前 Start/Stop/Apply 完成",
            },
            RouterErrorCode::LFC_0002 => ErrorMetadata {
                code: "CR-LFC-0002",
                scenario: "端口 PID 路径不是受管进程",
                http_status: 409,
                retry: RetryPolicy::Operator,
                agent_action: "不终止未知进程，人工确认",
            },
            RouterErrorCode::LFC_0003 => ErrorMetadata {
                code: "CR-LFC-0003",
                scenario: "存在活动连接，操作被延期",
                http_status: 409,
                retry: RetryPolicy::After,
                agent_action: "等请求结束再切换/停止",
            },
            RouterErrorCode::LFC_0004 => ErrorMetadata {
                code: "CR-LFC-0004",
                scenario: "Router Host 启动失败",
                http_status: 503,
                retry: RetryPolicy::Bounded,
                agent_action: "检查端口、数据目录、SQLite",
            },
            RouterErrorCode::LFC_0005 => ErrorMetadata {
                code: "CR-LFC-0005",
                scenario: "受管进程无法正常停止",
                http_status: 500,
                retry: RetryPolicy::Operator,
                agent_action: "验证 PID/路径后再处理",
            },
            RouterErrorCode::LFC_0006 => ErrorMetadata {
                code: "CR-LFC-0006",
                scenario: "聚合健康检查失败",
                http_status: 503,
                retry: RetryPolicy::Bounded,
                agent_action: "按 component 字段修复 Host/CLI/DB",
            },
            RouterErrorCode::LFC_0007 => ErrorMetadata {
                code: "CR-LFC-0007",
                scenario: "原子切换后 smoke 失败",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "立即执行自动回滚",
            },
            RouterErrorCode::LFC_0008 => ErrorMetadata {
                code: "CR-LFC-0008",
                scenario: "自动回滚未恢复旧健康状态",
                http_status: 500,
                retry: RetryPolicy::Operator,
                agent_action: "停止进一步写入并按快照人工恢复",
            },
            RouterErrorCode::MIG_0001 => ErrorMetadata {
                code: "CR-MIG-0001",
                scenario: "检测到旧基线不是 1.7.10/预期 Sub2API",
                http_status: 409,
                retry: RetryPolicy::No,
                agent_action: "重新调研该实际版本，禁止套用本方案",
            },
            RouterErrorCode::MIG_0002 => ErrorMetadata {
                code: "CR-MIG-0002",
                scenario: "旧控制面对象导出不完整",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "保持旧服务，按对象重导",
            },
            RouterErrorCode::MIG_0003 => ErrorMetadata {
                code: "CR-MIG-0003",
                scenario: "旧 OAuth/API 凭据无法无损转换",
                http_status: 422,
                retry: RetryPolicy::No,
                agent_action: "中止切换；实现该 provider converter",
            },
            RouterErrorCode::MIG_0004 => ErrorMetadata {
                code: "CR-MIG-0004",
                scenario: "group/composite route 转换不一致",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "比对规范化 route snapshot",
            },
            RouterErrorCode::MIG_0005 => ErrorMetadata {
                code: "CR-MIG-0005",
                scenario: "新 SQLite/CLI 状态引用完整性失败",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "回滚新状态并修迁移器",
            },
            RouterErrorCode::MIG_0006 => ErrorMetadata {
                code: "CR-MIG-0006",
                scenario: "私有 18081 shadow 测试失败",
                http_status: 502,
                retry: RetryPolicy::Bounded,
                agent_action: "保持旧 18080 在线，修新栈",
            },
            RouterErrorCode::MIG_0007 => ErrorMetadata {
                code: "CR-MIG-0007",
                scenario: "18080 原子端口切换失败",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "自动重新启动旧 Sub2API 栈",
            },
            RouterErrorCode::MIG_0008 => ErrorMetadata {
                code: "CR-MIG-0008",
                scenario: "旧负载仍是回滚依赖，禁止清理",
                http_status: 409,
                retry: RetryPolicy::After,
                agent_action: "完成稳定观察和回滚演练后再清理",
            },
            RouterErrorCode::LOG_0001 => ErrorMetadata {
                code: "CR-LOG-0001",
                scenario: "JSONL 日志 sink 无法打开/写入",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "修复日志目录/磁盘；同时写 Windows Event fallback",
            },
            RouterErrorCode::LOG_0002 => ErrorMetadata {
                code: "CR-LOG-0002",
                scenario: "日志事件序列化失败",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "修复字段类型，保留最小 fallback event",
            },
            RouterErrorCode::LOG_0003 => ErrorMetadata {
                code: "CR-LOG-0003",
                scenario: "敏感信息 redaction 检测失败",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "丢弃该事件内容，只记 code/request_id",
            },
            RouterErrorCode::LOG_0004 => ErrorMetadata {
                code: "CR-LOG-0004",
                scenario: "日志轮转/保留任务失败",
                http_status: 500,
                retry: RetryPolicy::Bounded,
                agent_action: "保留当前文件并重试轮转",
            },
            RouterErrorCode::LOG_0005 => ErrorMetadata {
                code: "CR-LOG-0005",
                scenario: "下游与 CLI request correlation 丢失",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "修复 header/trace 传播",
            },
            RouterErrorCode::LOG_0006 => ErrorMetadata {
                code: "CR-LOG-0006",
                scenario: "请求缺少唯一 terminal span",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "修复 finally/Drop guard",
            },
            RouterErrorCode::SYS_0001 => ErrorMetadata {
                code: "CR-SYS-0001",
                scenario: "未捕获 panic/内部不变量破坏",
                http_status: 500,
                retry: RetryPolicy::No,
                agent_action: "用 request_id 定位 panic，补显式错误分支",
            },
            RouterErrorCode::SYS_0002 => ErrorMetadata {
                code: "CR-SYS-0002",
                scenario: "必需 worker/thread 无法创建",
                http_status: 503,
                retry: RetryPolicy::Bounded,
                agent_action: "检查系统资源并降低并发",
            },
            RouterErrorCode::SYS_0003 => ErrorMetadata {
                code: "CR-SYS-0003",
                scenario: "文件句柄/内存/任务槽耗尽",
                http_status: 503,
                retry: RetryPolicy::After,
                agent_action: "释放泄漏资源并限流",
            },
            RouterErrorCode::SYS_0004 => ErrorMetadata {
                code: "CR-SYS-0004",
                scenario: "系统时间异常导致 OAuth/TTL 无法判断",
                http_status: 503,
                retry: RetryPolicy::Operator,
                agent_action: "同步系统时间后重试",
            },
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct ErrorMetadata {
    pub code: &'static str,
    pub scenario: &'static str,
    pub http_status: u16,
    pub retry: RetryPolicy,
    pub agent_action: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RetryPolicy {
    No,
    Bounded,
    After,
    Operator,
}

impl fmt::Display for RouterErrorCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

pub fn error_catalog_json() -> serde_json::Value {
    serde_json::json!({
        "version": "2.0.0",
        "codes": RouterErrorCode::ALL.iter().map(|code| {
            let metadata = code.metadata();
            serde_json::json!({
                "code": metadata.code,
                "scenario": metadata.scenario,
                "http": metadata.http_status,
                "retry": metadata.retry,
                "node": chain_node(*code),
                "agent_action": metadata.agent_action,
            })
        }).collect::<Vec<_>>(),
    })
}

pub fn from_code(code: &str) -> Option<RouterErrorCode> {
    RouterErrorCode::ALL
        .iter()
        .copied()
        .find(|candidate| candidate.as_str().eq_ignore_ascii_case(code))
}

pub fn chain_node(code: RouterErrorCode) -> &'static str {
    if code.as_str().starts_with("CR-REQ") {
        return "request";
    }
    if code.as_str().starts_with("CR-VAL") {
        return "validation";
    }
    if code.as_str().starts_with("CR-AUT") {
        return "auth";
    }
    if code.as_str().starts_with("CR-OAU") {
        return "oauth";
    }
    if code.as_str().starts_with("CR-CFG") {
        return "config";
    }
    if code.as_str().starts_with("CR-RTE") {
        return "route";
    }
    if code.as_str().starts_with("CR-CLI") {
        return "cli";
    }
    if code.as_str().starts_with("CR-PRX") {
        return "proxy";
    }
    if code.as_str().starts_with("CR-STR") {
        return "stream";
    }
    if code.as_str().starts_with("CR-ADP") {
        return "adapter";
    }
    if code.as_str().starts_with("CR-UP") {
        return "upstream";
    }
    if code.as_str().starts_with("CR-STO") {
        return "storage";
    }
    if code.as_str().starts_with("CR-USE") {
        return "usage";
    }
    if code.as_str().starts_with("CR-LFC") {
        return "lifecycle";
    }
    if code.as_str().starts_with("CR-MIG") {
        return "migration";
    }
    if code.as_str().starts_with("CR-LOG") {
        return "logging";
    }
    "system"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_codes_and_scenarios_are_unique() {
        let mut codes: Vec<_> = RouterErrorCode::ALL
            .iter()
            .map(|code| code.as_str())
            .collect();
        let count = codes.len();
        codes.sort_unstable();
        codes.dedup();
        assert_eq!(codes.len(), count);
        let mut scenarios: Vec<_> = RouterErrorCode::ALL
            .iter()
            .map(|code| code.metadata().scenario)
            .collect();
        scenarios.sort_unstable();
        scenarios.dedup();
        assert_eq!(scenarios.len(), count);
    }

    #[test]
    fn catalog_is_complete_and_json_serializable() {
        let value = error_catalog_json();
        assert_eq!(
            value["codes"].as_array().map(Vec::len),
            Some(RouterErrorCode::ALL.len())
        );
        assert!(from_code("CR-REQ-0001").is_some());
        assert!(from_code("cr-unknown-9999").is_none());
    }
}
