listen_addresses = '127.0.0.1'
port = 15432
max_connections = 80
shared_buffers = 128MB
dynamic_shared_memory_type = windows
password_encryption = 'scram-sha-256'
timezone = 'Asia/Shanghai'
log_timezone = 'Asia/Shanghai'
logging_collector = off
log_min_messages = warning
