bind 127.0.0.1
protected-mode yes
port 16379
timeout 0
tcp-keepalive 60
daemonize no
loglevel notice
databases 4
dir .
dbfilename dump.rdb
appendonly yes
appendfilename appendonly.aof
appendfsync everysec
save 3600 1 300 100 60 10000
